name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_crates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [feos-core, feos-dft]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release -p ${{ matrix.crate }}
      - name: Run tests
        run: cargo test --release -p ${{ matrix.crate }}

  test_python_bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - name: Build
        run: cargo build --release --manifest-path py-feos/Cargo.toml
      - name: Run tests
        run: cargo test --release --manifest-path py-feos/Cargo.toml

  test_models:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [pcsaft, epcsaft, gc_pcsaft, pets, uvtheory, saftvrqmie, saftvrmie, multiparameter]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --features ${{ matrix.model }}
      - name: Run tests
        run: cargo test --release --features ${{ matrix.model }}

  test_models_dft:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [pcsaft, gc_pcsaft]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --features "${{ matrix.model }} dft"
      - name: Run tests
        run: cargo test --release --features "${{ matrix.model }} dft"
