name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_crates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [feos-core, feos-dft]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release -p ${{ matrix.crate }}
      - name: Run tests
        run: cargo test --release -p ${{ matrix.crate }}

  test_models:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [pcsaft, gc_pcsaft, pets, uvtheory]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --features ${{ matrix.model }}
      - name: Run tests
        run: cargo test --release --features ${{ matrix.model }}

  test_models_dft:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [pcsaft, gc_pcsaft]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --features "${{ matrix.model }} dft"
      - name: Run tests
        run: cargo test --release --features "${{ matrix.model }} dft"
